// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faqugbqthcorlmqdifxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcXVnYnF0aGNvcmxtcWRpZnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjgzNzEsImV4cCI6MjA2MjAwNDM3MX0.Zpu_PKMOAaAqUA2C89YRfdDcOZGiTIytw4fC245cC_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);